export interface Guidance {
  text: string;
}

export interface LuckyItem {
  name: string;
}

export interface LuckyColour {
  name: string;
  hex: string;
  description: string;
}

export const dailyGuidances: Guidance[] = [
  { text: "Embrace the unexpected today; a small detour may lead to a wonderful new discovery." },
  { text: "Your energy is a beacon. Shine brightly and let others draw warmth from your enthusiasm." },
  { text: "Take a deep breath and trust the timing of your life; everything is unfolding as it should." },
  { text: "A kind word spoken today will ripple out and return to you in unexpected, beautiful ways." },
  { text: "Focus on progress, not perfection. Every small step forward is a victory worth celebrating." },
  { text: "You possess the strength to handle whatever this day brings with grace and wisdom." },
  { text: "Be open to learning something new today; inspiration is hiding in the most ordinary places." },
  { text: "A creative spark is waiting to be lit. Allow yourself time to play and think freely." },
  { text: "Nurture your connections today. A short message to a friend can brighten both your days." },
  { text: "Give yourself permission to slow down and appreciate the present moment's quiet beauty." },
  { text: "Your unique perspective is needed. Don't be afraid to voice your authentic thoughts." },
  { text: "An opportunity for growth is near. Step forward with courage and an open heart." },
  { text: "Today is a perfect day to let go of what you cannot control and focus on what you can." },
  { text: "Trust your intuition today. That subtle inner nudge is guiding you toward clarity." },
  { text: "Your efforts are building a solid foundation. Keep going; your persistence will pay off." },
  { text: "Carry a sense of curiosity with you. Ask questions and explore new angles today." },
  { text: "A simple act of self-care will replenish your spirit and bring peaceful clarity." },
  { text: "Notice the small joys around you—a warm cup of tea, a smile, or a beautiful ray of light." },
  { text: "You are more resilient than you realize. Trust your ability to adapt and thrive." },
  { text: "Clear your mind of old doubts. Today brings a fresh slate and brand-new possibilities." },
  { text: "Your presence is a gift to those around you. Walk with quiet confidence today." },
  { text: "Direct your focus toward gratitude today; it will transform ordinary moments into blessings." },
  { text: "A gentle, patient approach will solve more challenges today than force ever could." },
  { text: "Allow your passion to guide your actions. Even a small passion project can spark joy." },
  { text: "Remember that mistakes are simply proof that you are trying and growing." },
  { text: "Keep your eyes on the horizon. A positive change in your professional life is brewing." },
  { text: "Lighten your load today. Release old resentments to make room for new blessings." },
  { text: "A genuine smile is your best asset today. Use it to connect and lift others up." },
  { text: "Listen deeply to others today. You might hear exactly what you needed to hear yourself." },
  { text: "Stand tall and speak your truth with kindness. Your integrity is your superpower." },
  { text: "Take pride in how far you have come. Your journey is uniquely beautiful." },
  { text: "A burst of clear focus will help you complete a task you have been putting off." },
  { text: "Let your humor shine today. Laughter is the shortest distance between two people." },
  { text: "Your heart knows the way. Align your tasks today with your deepest personal goals." },
  { text: "Seek out a moment of solitude today to check in with your mind, body, and soul." },
  { text: "Your analytical mind is sharp today. Use it to untangle a complex problem with ease." },
  { text: "Be gentle with yourself. You are doing the best you can, and that is more than enough." },
  { text: "A conversation today could plant the seeds for a highly successful future collaboration." },
  { text: "Choose optimism today. Looking on the bright side will draw positive energy to you." },
  { text: "Your hard work is being noticed by key people. Keep polishing your craft." },
  { text: "Step outside for a few moments today and connect with the grounding energy of nature." },
  { text: "A pleasant surprise is on its way, bringing a touch of magic to your ordinary routine." },
  { text: "Be the anchor of calm in busy surroundings today. Your peace is contagious." },
  { text: "Trust your creative insights. A brilliant idea is ready to find its form." },
  { text: "You are worthy of happiness, success, and love. Never let anyone make you doubt it." },
  { text: "Today is ripe for organization. Clear your physical space to invite mental clarity." },
  { text: "Celebrate someone else's achievement today. Joy shared is joy doubled." },
  { text: "Your dedication to self-improvement is paying off in ways you cannot yet see." },
  { text: "Do something today simply for the joy of doing it, with no expectation of outcome." },
  { text: "A decision you make today will lead to a more balanced and harmonious week ahead." },
  { text: "Let your enthusiasm be contagious. Your energy can inspire others to greatness." },
  { text: "Forgive yourself for yesterday's shortcomings. Today is a brand-new beginning." },
  { text: "You have the power to create a positive environment wherever you walk today." },
  { text: "An unexpected message from the past will bring a warm wave of nostalgia and joy." },
  { text: "Nurture your body with nutritious food, fresh water, and gentle movement today." },
  { text: "Your ability to listen and show empathy is a rare, precious strength. Use it well." },
  { text: "Stay committed to your personal boundaries. Saying no can be the ultimate act of self-care." },
  { text: "An avenue of creative expression is opening up for you. Step in with playful courage." },
  { text: "Keep your mind open to alternative solutions. The answer is simpler than you think." },
  { text: "You are an force of positive change. Believe in your capability to make a difference." }
];

export const luckyItems: LuckyItem[] = [
  { name: "A silver or metal coin" },
  { name: "A handwritten note or card" },
  { name: "A reusable water bottle" },
  { name: "A pair of comfortable walking shoes" },
  { name: "A favorite gemstone or smooth stone" },
  { name: "A custom bookmark" },
  { name: "A delicate keychain" },
  { name: "A small pocket notebook" },
  { name: "A pair of reliable headphones" },
  { name: "A green houseplant or leaf" },
  { name: "A classic mechanical pencil" },
  { name: "A scented candle (mint or lavender)" },
  { name: "A silver ring or bracelet" },
  { name: "A comforting mug of warm herbal tea" },
  { name: "A colorful paperclip" },
  { name: "A soft, freshly washed scarf" },
  { name: "A piece of dark chocolate" },
  { name: "A favorite printed photograph" },
  { name: "A small container of lip balm" },
  { name: "A canvas tote bag" },
  { name: "A pair of sunglasses" },
  { name: "A simple wooden coaster" },
  { name: "A retro postal stamp" },
  { name: "A small leather wallet or cardholder" },
  { name: "A brass paperweight" },
  { name: "A fresh red or green apple" },
  { name: "A vintage analog watch" },
  { name: "A pocket-sized mirror" },
  { name: "A small bottle of essential oil" },
  { name: "A seashell collected from a beach" },
  { name: "A classic paperback novel" },
  { name: "A set of colorful sticky notes" },
  { name: "A small metal ruler" },
  { name: "A patterned pocket square or bandana" },
  { name: "A mechanical keyboard keycap" },
  { name: "A thermos of filter coffee" },
  { name: "A small ceramic dish" },
  { name: "A protective talisman or charm" },
  { name: "A simple fountain pen" },
  { name: "A local transit card or ticket" },
  { name: "A small pouch of dried lavender leaves" },
  { name: "A miniature hourglass" },
  { name: "A smooth-writing gel pen" },
  { name: "A set of high-quality dice" },
  { name: "A favorite pin or enamel badge" },
  { name: "A hand-poured glass figurine" },
  { name: "A reliable umbrella" },
  { name: "A piece of fresh mint leaf" },
  { name: "A simple leather-bound journal" },
  { name: "A miniature lucky cat figurine" },
  { name: "A simple woven fabric bracelet" },
  { name: "A clean microfiber cloth" },
  { name: "A glass marble with swirling colors" },
  { name: "A silver spoon or stirring rod" },
  { name: "A packet of botanical flower seeds" },
  { name: "A wooden comb or hair brush" },
  { name: "A ceramic tea light holder" },
  { name: "A miniature sketchpad" },
  { name: "A protective phone case" },
  { name: "A piece of raw quartz or crystal" }
];

export const luckyColours: LuckyColour[] = [
  { name: "Celestial Blue", hex: "#3B82F6", description: "Deep, atmospheric sky blue representing wisdom and loyalty." },
  { name: "Sage Green", hex: "#86EFAC", description: "Gentle, healing light herb green bringing renewal and peace." },
  { name: "Amber Sun", hex: "#F59E0B", description: "Warm, energy-giving golden amber symbolizing warmth and growth." },
  { name: "Mystic Violet", hex: "#8B5CF6", description: "Creative, spiritual purple that enhances intuition and imagination." },
  { name: "Crimson Coral", hex: "#EF4444", description: "Vibrant, action-oriented coral red generating drive and courage." },
  { name: "Peach Cream", hex: "#FDBA74", description: "Soft, comforting peach orange supporting friendliness and harmony." },
  { name: "Emerald Pine", hex: "#10B981", description: "Prosperous, grounding dark forest green encouraging stability." },
  { name: "Charcoal Slate", hex: "#4B5563", description: "Elegant, stable cool dark slate providing structure and composure." },
  { name: "Rose Quartz", hex: "#FDA4AF", description: "Loving, stress-relieving soft rose pink bringing kindness and care." },
  { name: "Citron Yellow", hex: "#FDE047", description: "Brilliant, clear-thinking yellow sparking optimism and lucidity." },
  { name: "Teal Oasis", hex: "#14B8A6", description: "Peaceful, rejuvenating ocean teal cultivating calm and relief." },
  { name: "Warm Terracotta", hex: "#D97706", description: "Earthbound, warm rustic orange-brown inspiring safety and depth." },
  { name: "Pure Platinum", hex: "#CBD5E1", description: "Reflective, clarifying metallic light grey representing honesty and clarity." },
  { name: "Midnight Indigo", hex: "#312E81", description: "Deep, intuitive dark purple-blue embodying introspection and sleep." },
  { name: "Earthy Ochre", hex: "#CA8A04", description: "Abundant, stable gold-yellow earth tone carrying abundance and support." }
];
